package ch.tarvynanalytics.graphs.algos;

import ch.tarvynanalytics.graphs.algos.model.ChangeSignal;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Oracle B (§8.2 of the S3 spec): cross-language parity against the spike. The committed
 * fixtures were generated by {@code spike/export_s3_fixture.py} from the probe's own
 * {@code _corr_from_window} on a seeded planted-change panel. The Java side is fed the
 * <em>matrices</em> and recomputes the change series through the full detector pipeline, then
 * asserts it bar-for-bar against the expected values (the engine recomputes what is checked —
 * the change values are never fed in). The detector must also fire within the planted fused
 * regime — the end-to-end mechanics claim.
 */
class ChangeMetricsFixtureParityTest {

    private static final double WEIGHTED_TOL = 1e-9;   // §1.5: ~100x the proven ~9e-12 worst case
    private static final double EXACT_TOL = 1e-12;
    private static final int CALM_TRANSITIONS = 5;     // seq 0..4 are calm->calm (pre-change)
    private static final int EXPECTED_FIRE_SEQ = 5;    // the calm->fused jump

    @Test
    void detectorPipeline_ReproducesSpikeChangeSeries_AndFiresOnPlantedChange() {
        List<double[]> upperRows = readMatrices();
        List<Expected> expected = readExpected();
        int n = upperRows.size();
        int m = orderFromPairCount(upperRows.get(0).length);
        assertEquals(expected.size(), n - 1, "one expected row per transition");

        double[][][] matrices = new double[n][][];
        for (int i = 0; i < n; i++) {
            matrices[i] = toSymmetric(upperRows.get(i), m);
        }

        // Calibrate on the calm prefix (the expected calm weighted_change / density series).
        double[] calmWeighted = new double[CALM_TRANSITIONS];
        double[] calmDensity = new double[CALM_TRANSITIONS];
        for (int i = 0; i < CALM_TRANSITIONS; i++) {
            calmWeighted[i] = expected.get(i).weightedChange;
            calmDensity[i] = expected.get(i).densityLevel;
        }
        Calibration cal = ChangeDetectors.calibrate(calmWeighted, calmDensity, DetectorConfig.equity());
        ChangeDetector detector = ChangeDetectors.create(m, DetectorConfig.equity(), cal);

        assertNull(detector.onMatrix(matrices[0]), "first matrix has no transition");
        for (int i = 1; i < n; i++) {
            ChangeSignal s = detector.onMatrix(matrices[i]);
            assertNotNull(s);
            int seq = i - 1;
            assertEquals(seq, (int) s.seq());
            Expected e = expected.get(seq);
            assertClose(e.weightedChange, s.metrics().weightedChange(), WEIGHTED_TOL, "weighted_change@" + seq);
            assertClose(e.densityLevel, s.metrics().densityLevel(), EXACT_TOL, "density_level@" + seq);
            assertClose(e.edgeXor, s.metrics().edgeXor(), EXACT_TOL, "edge_xor@" + seq);
            assertEquals(e.nComponents, s.metrics().nComponents(), "n_components@" + seq);
            assertClose(e.largestComponentFraction, s.metrics().largestComponentFraction(), EXACT_TOL, "lcf@" + seq);
        }

        assertTrue(detector.firstFire().isPresent(), "detector must fire on the planted change");
        assertEquals((long) EXPECTED_FIRE_SEQ, detector.firstFire().get().seq(),
                "fires at the calm->fused jump");
        // sanity: the fire happens after the calm calibration window and on an elevated change
        assertTrue(detector.firstFire().get().metrics().weightedChange()
                > expected.get(CALM_TRANSITIONS - 1).weightedChange,
                "fire change exceeds the calm baseline");
    }

    // ---- fixture parsing (hand-rolled, lean-deps; mirrors CorrelationCsv) ----

    private static int orderFromPairCount(int pairs) {
        // pairs = m(m-1)/2  =>  m = (1 + sqrt(1 + 8*pairs)) / 2
        return (int) Math.round((1 + Math.sqrt(1 + 8.0 * pairs)) / 2.0);
    }

    private static double[][] toSymmetric(double[] upper, int m) {
        double[][] c = new double[m][m];
        for (int i = 0; i < m; i++) {
            c[i][i] = 1.0;
        }
        int idx = 0;
        for (int i = 0; i < m; i++) {
            for (int j = i + 1; j < m; j++) {
                c[i][j] = upper[idx];
                c[j][i] = upper[idx];
                idx++;
            }
        }
        return c;
    }

    private static List<double[]> readMatrices() {
        List<double[]> rows = new ArrayList<>();
        for (String line : dataLines("/s3_change_matrices.csv")) {
            String[] parts = line.split(",");
            double[] upper = new double[parts.length - 1];   // drop the leading seq column
            for (int i = 1; i < parts.length; i++) {
                upper[i - 1] = Double.parseDouble(parts[i].trim());
            }
            rows.add(upper);
        }
        return rows;
    }

    private static List<Expected> readExpected() {
        List<Expected> rows = new ArrayList<>();
        for (String line : dataLines("/s3_change_expected.csv")) {
            String[] p = line.split(",");
            rows.add(new Expected(
                    Double.parseDouble(p[0].trim()), Double.parseDouble(p[1].trim()),
                    Double.parseDouble(p[2].trim()), Integer.parseInt(p[3].trim()),
                    Double.parseDouble(p[4].trim())));
        }
        return rows;
    }

    /** All non-comment, non-header, non-blank lines of a classpath CSV resource. */
    private static List<String> dataLines(String resource) {
        List<String> out = new ArrayList<>();
        try (InputStream in = ChangeMetricsFixtureParityTest.class.getResourceAsStream(resource)) {
            assertNotNull(in, "missing test resource " + resource);
            BufferedReader r = new BufferedReader(new InputStreamReader(in, StandardCharsets.UTF_8));
            String line;
            boolean headerSeen = false;
            while ((line = r.readLine()) != null) {
                String t = line.strip();
                if (t.isEmpty() || t.startsWith("#")) {
                    continue;
                }
                if (!headerSeen) {
                    headerSeen = true;   // the first non-comment line is the column header
                    continue;
                }
                out.add(t);
            }
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
        return out;
    }

    private static void assertClose(double expected, double actual, double tol, String where) {
        if (Double.isNaN(expected)) {
            assertTrue(Double.isNaN(actual), where + ": expected NaN but was " + actual);
        } else {
            assertEquals(expected, actual, tol, where);
        }
    }

    private record Expected(double weightedChange, double densityLevel, double edgeXor,
                            int nComponents, double largestComponentFraction) {
    }
}
